# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k160tfbg676-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/zcy/zcy_project/zcy_project.cache/wt [current_project]
set_property parent.project_path /home/zcy/zcy_project/zcy_project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/zcy/zcy_project/zcy_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/zcy/zcy_project/zcy_project.srcs/sources_1/imports/vga3/map.coe
add_files -quiet /home/zcy/zcy_project/zcy_project.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files /home/zcy/zcy_project/zcy_project.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp]
read_mem /home/zcy/zcy_project/zcy_project.srcs/sources_1/imports/vga3/frame.mif
read_verilog -library xil_defaultlib {
  /home/zcy/zcy_project/zcy_project.srcs/sources_1/imports/vga3/MyMC14495.vf
  /home/zcy/zcy_project/zcy_project.srcs/sources_1/imports/vga3/Mux4to14b.vf
  /home/zcy/zcy_project/zcy_project.srcs/sources_1/imports/vga3/Mux4to1.vf
  /home/zcy/zcy_project/zcy_project.srcs/sources_1/imports/vga3/vga_sync.v
  /home/zcy/zcy_project/zcy_project.srcs/sources_1/imports/vga3/vga_display.v
  /home/zcy/zcy_project/zcy_project.srcs/sources_1/imports/vga3/HEXtoBCD.v
  /home/zcy/zcy_project/zcy_project.srcs/sources_1/imports/vga3/disp_num.vf
  /home/zcy/zcy_project/zcy_project.srcs/sources_1/imports/vga3/clkdiv.v
  /home/zcy/zcy_project/zcy_project.srcs/sources_1/imports/vga3/Top.v
  /home/zcy/zcy_project/zcy_project.srcs/sources_1/imports/vga3/F44MS49IFLC35N1.v
  /home/zcy/zcy_project/zcy_project.srcs/sources_1/new/Buzzer.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/zcy/zcy_project/zcy_project.srcs/constrs_1/imports/vga3/top.xdc
set_property used_in_implementation false [get_files /home/zcy/zcy_project/zcy_project.srcs/constrs_1/imports/vga3/top.xdc]


synth_design -top Top -part xc7k160tfbg676-3


write_checkpoint -force -noxdef Top.dcp

catch { report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb }
